/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_CEC2019c */

#ifndef _Included_util_CEC2019c
#define _Included_util_CEC2019c
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_CEC2019c
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_util_CEC2019c_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     util_CEC2019c
 * Method:    fitness
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_util_CEC2019c_fitness
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
